/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DotSymbol: typeof import('./../components/DotSymbol.vue')['default']
    DrawnSymbol: typeof import('./../components/DrawnSymbol.vue')['default']
    Icon: typeof import('./../components/Icon.vue')['default']
    Navigation: typeof import('./../components/Navigation.vue')['default']
    NoiseSymbol: typeof import('./../components/NoiseSymbol.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SegmentDays: typeof import('./../components/SegmentDays.vue')['default']
    SegmentHours: typeof import('./../components/SegmentHours.vue')['default']
    SegmentMinutes: typeof import('./../components/SegmentMinutes.vue')['default']
    SegmentMonths: typeof import('./../components/SegmentMonths.vue')['default']
    SegmentSeconds: typeof import('./../components/SegmentSeconds.vue')['default']
    SegmentYears: typeof import('./../components/SegmentYears.vue')['default']
    StapledSymbol: typeof import('../components/NoiseSymbol.vue')['default']
    Time: typeof import('./../components/Time.vue')['default']
  }
}
