<template>
  <div class="grid grid-cols-4">
    <div v-for="(clock, index) in clockRotations" :key="index" class="relative bg-stone-200 shadow rounded-full size-5">
      <div
        class="top-1/2 left-1/2 absolute bg-black rounded-full w-0.5 h-2.5 origin-bottom transition-transform duration-300 ease-in-out transform" :style="`transform: translate(-50%, -100%) rotate(${clock.hour}deg)`" />
      <div
        class="top-1/2 left-1/2 absolute bg-black rounded-full w-0.5 h-2.5 origin-bottom transition-transform duration-300 ease-in-out transform" :style="`transform: translate(-50%, -100%) rotate(${(clock.minute)}deg)`" />
    </div>
  </div>
</template>

<script setup lang="ts">
import type { SymbolTypes } from '../composables/useDots'

const props = defineProps<{
  symbol: string | number | undefined
}>()

const rotations = {
  'horizontal': { hour: 0, minute: 180 },
  'vertical': { hour: 90, minute: 270 },
  'top-left': { hour: 180, minute: 270 },
  'top-right': { hour: 0, minute: 270 },
  'bottom-left': { hour: 180, minute: 90 },
  'bottom-right': { hour: 0, minute: 90 },
  'default': { hour: 45, minute: 45 },
} as const

const symbols: Record<SymbolTypes, (keyof typeof rotations)[]> = {
  0: [
    'bottom-right',
    'horizontal',
    'horizontal',
    'bottom-left',
    'vertical',
    'bottom-right',
    'bottom-left',
    'vertical',
    'vertical',
    'vertical',
    'vertical',
    'vertical',
    'vertical',
    'vertical',
    'vertical',
    'vertical',
    'vertical',
    'top-right',
    'top-left',
    'vertical',
    'top-right',
    'horizontal',
    'horizontal',
    'top-left',
  ],
  1: [
    'bottom-right',
    'horizontal',
    'bottom-left',
    'default',
    'top-right',
    'bottom-left',
    'vertical',
    'default',
    'default',
    'vertical',
    'vertical',
    'default',
    'default',
    'vertical',
    'vertical',
    'default',
    'bottom-right',
    'top-left',
    'top-right',
    'bottom-left',
    'top-right',
    'horizontal',
    'horizontal',
    'top-left',
  ],
  2: [
    'bottom-right',
    'horizontal',
    'horizontal',
    'bottom-left',
    'top-right',
    'horizontal',
    'bottom-left',
    'vertical',
    'bottom-right',
    'horizontal',
    'top-left',
    'vertical',
    'vertical',
    'bottom-right',
    'horizontal',
    'top-left',
    'vertical',
    'top-right',
    'horizontal',
    'bottom-left',
    'top-right',
    'horizontal',
    'horizontal',
    'top-left',
  ],
  3: [
    'bottom-right',
    'horizontal',
    'horizontal',
    'bottom-left',
    'top-right',
    'horizontal',
    'bottom-left',
    'vertical',
    'default',
    'bottom-right',
    'top-left',
    'vertical',
    'default',
    'top-right',
    'bottom-left',
    'vertical',
    'bottom-right',
    'horizontal',
    'top-left',
    'vertical',
    'top-right',
    'horizontal',
    'horizontal',
    'top-left',
  ],
  4: [
    'bottom-right',
    'bottom-left',
    'bottom-right',
    'bottom-left',
    'vertical',
    'vertical',
    'vertical',
    'vertical',
    'vertical',
    'top-right',
    'top-left',
    'vertical',
    'top-right',
    'horizontal',
    'bottom-left',
    'vertical',
    'default',
    'default',
    'vertical',
    'vertical',
    'default',
    'default',
    'top-right',
    'top-left',
  ],
  5: [
    'bottom-right',
    'horizontal',
    'horizontal',
    'bottom-left',
    'vertical',
    'bottom-right',
    'horizontal',
    'top-left',
    'vertical',
    'top-right',
    'horizontal',
    'bottom-left',
    'top-right',
    'horizontal',
    'bottom-left',
    'vertical',
    'bottom-right',
    'horizontal',
    'top-left',
    'vertical',
    'top-right',
    'horizontal',
    'horizontal',
    'top-left',
  ],
  6: [
    'bottom-right',
    'horizontal',
    'horizontal',
    'bottom-left',
    'vertical',
    'bottom-right',
    'horizontal',
    'top-left',
    'vertical',
    'top-right',
    'horizontal',
    'bottom-left',
    'vertical',
    'bottom-right',
    'bottom-left',
    'vertical',
    'vertical',
    'top-right',
    'top-left',
    'vertical',
    'top-right',
    'horizontal',
    'horizontal',
    'top-left',
  ],
  7: [
    'bottom-right',
    'horizontal',
    'horizontal',
    'bottom-left',
    'top-right',
    'horizontal',
    'bottom-left',
    'vertical',
    'default',
    'default',
    'vertical',
    'vertical',
    'default',
    'default',
    'vertical',
    'vertical',
    'default',
    'default',
    'vertical',
    'vertical',
    'default',
    'default',
    'top-right',
    'top-left',
  ],
  8: [
    'bottom-right',
    'horizontal',
    'horizontal',
    'bottom-left',
    'vertical',
    'bottom-right',
    'bottom-left',
    'vertical',
    'vertical',
    'top-right',
    'top-left',
    'vertical',
    'vertical',
    'bottom-right',
    'bottom-left',
    'vertical',
    'vertical',
    'top-right',
    'top-left',
    'vertical',
    'top-right',
    'horizontal',
    'horizontal',
    'top-left',
  ],
  9: [
    'bottom-right',
    'horizontal',
    'horizontal',
    'bottom-left',
    'vertical',
    'bottom-right',
    'bottom-left',
    'vertical',
    'vertical',
    'top-right',
    'top-left',
    'vertical',
    'top-right',
    'horizontal',
    'bottom-left',
    'vertical',
    'bottom-right',
    'horizontal',
    'top-left',
    'vertical',
    'top-right',
    'horizontal',
    'horizontal',
    'top-left',
  ],
  arrowLeft: ['horizontal', 'horizontal', 'horizontal', 'horizontal', 'horizontal', 'horizontal', 'horizontal', 'horizontal'], // TODO: still a placeholder setup
  arrowRight: ['horizontal', 'horizontal', 'horizontal', 'horizontal', 'horizontal', 'horizontal', 'horizontal', 'horizontal'], // TODO: still a placeholder setup
  colon: ['horizontal', 'horizontal', 'horizontal', 'horizontal', 'horizontal', 'horizontal', 'horizontal', 'horizontal'], // TODO: still a placeholder setup
  dash: ['horizontal', 'horizontal', 'horizontal', 'horizontal', 'horizontal', 'horizontal', 'horizontal', 'horizontal'], // TODO: still a placeholder setup
  dot: ['horizontal', 'horizontal', 'horizontal', 'horizontal', 'horizontal', 'horizontal', 'horizontal', 'horizontal'], // TODO: still a placeholder setup
}

const clockRotations = computed(() => {
  const symbol = (props.symbol ?? 'default') as SymbolTypes
  if (!symbols[symbol]) {
    return []
  }
  return symbols[symbol].map(key => ({
    hour: rotations[key].hour,
    minute: rotations[key].minute,
  }))
})
</script>
